Sync release branch updates and deployment checks
Sync release branch updates and deployment checks

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,14 +7,17 @@ on:
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
     inputs:
-        app:
-            description: 'App Name (jag-role-registry)'    
-            required: true
-            default: jag-role-registry
-        env:
-            description: 'Image Target Env'     
-            required: true
-            default: 'dev'
+      app:
+        description: 'App Name (jag-role-registry)'    
+        required: true
+        default: jag-role-registry
+      env:
+        type: choice
+        description: Image Target environment
+        options: 
+        - dev    
+        required: true
+        default: 'dev'
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -31,7 +34,7 @@ jobs:
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - name: Git Checkout
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
       
       # Get the version number which is prefixed with the Github release branches in format release/{version}
       - name: Get Release Version
@@ -57,8 +60,9 @@ jobs:
 
       # Set up JDK build environment
       - name: Set up JDK 11
-        uses: actions/setup-java@v1
+        uses: actions/setup-java@v3
         with:
+          distribution: 'temurin'
           java-version: 11
         
       # Runs build steps
@@ -73,7 +77,7 @@ jobs:
       
       #Login to OpenShift Container Repository - Kamloops (OC PROD)
       - name: Login to OpenShift Container Repository - Kamloops (OC PROD)
-        uses: docker/login-action@v1
+        uses: docker/login-action@v2
         with:
           registry: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}
           username: ${{secrets.OPENSHIFT_SA_USERNAME}}
@@ -94,7 +98,7 @@ jobs:
       
       #Login to OpenShift Container Repository - Calgary (OC DR)
       - name: Login to OpenShift Container Repository - Calgary (OC DR)
-        uses: docker/login-action@v1
+        uses: docker/login-action@v2
         with:
           registry: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY_DR}}
           username: ${{secrets.OPENSHIFT_SA_USERNAME}}
@@ -171,25 +175,25 @@ jobs:
 
       - name: Run Integration Tests
         env:
-          TEST_STARTER_URL: ${{ secrets.TEST_STARTER_URL }}
-          BASIC_AUTH_USER: ${{ secrets.BASIC_AUTH_USER }}
-          BASIC_AUTH_PASS: ${{ secrets.BASIC_AUTH_PASS }}
+          TEST_STARTER_URL: ${{secrets.TEST_STARTER_URL}}
+          BASIC_AUTH_USER: ${{secrets.BASIC_AUTH_USER}}
+          BASIC_AUTH_PASS: ${{secrets.BASIC_AUTH_PASS}}
         run: |
           RET=`curl --write-out '%{content_type}' --output TestErrors.zip --request GET --user ${BASIC_AUTH_USER}:${BASIC_AUTH_PASS} --url ${TEST_STARTER_URL}`
           if [ "$RET" = "application/zip" ]; then
-            echo "Status: Failed Integration Test(s) found!"
-            exit 1
+          echo "Status: Failed Integration Test(s) found!"
+          exit 1
           fi
-          if [ "$RET" = "application/json" ]; then
-            echo "Status: All Tests Passed"
+          if [[ "$RET" == *"json"* ]]; then
+          echo "Status: All Tests Passed"
           fi
-          if [ "$RET" != "application/zip" ] && [ "$RET" != "application/json" ]; then
-            echo "Received content_type is $RET, was expecting application/json or application/zip"
-            exit 1
+          if [ "$RET" != "application/zip" ] && [[ "$RET" != *"json"* ]]; then
+          echo "Received content_type is $RET, was expecting json or zip"
+          exit 1
           fi
 
       - name: Archive production artifacts
-        uses: actions/upload-artifact@v2
+        uses: actions/upload-artifact@v3.1.1
         if: failure()
         with:
           name: integration-tests-report
